### ISSUE TITLE
Určit co chceme vytvořit v rámci bloku 1

### ISSUE THREAD

**Issue by tomaskebrle** [madebyqwerty/.github#1]
- [ ] Udělat si schůzku na které se domluvíme na tom co chceme vytvořit v bloku 1

**Comment by vaclavparma** [comment]
- Login a register
- Role učitelů
- Základní design

**Comment by tomaskebrle** [comment]
- [ ] Struktura dat v databázi
- [ ] Začátek na OCR
- [ ] Začátek na frontendu
